ALTER TABLE 'roles' AUTO_INCREMENT = 1;
ALTER TABLE 'admin' AUTO_INCREMENT = 1;
ALTER TABLE 'writers' AUTO_INCREMENT = 1;
ALTER TABLE 'readers' AUTO_INCREMENT = 1;
ALTER TABLE 'users' AUTO_INCREMENT = 1;
ALTER TABLE 'categories' AUTO_INCREMENT = 1;
ALTER TABLE 'recipes' AUTO_INCREMENT = 1;